#!/bin/bash
# =============================================================================
# auto-compound.sh
# Runs nightly at 11:00 PM via launchd (after compound review)
#
# Full pipeline: backlog → PRD → tasks → implementation → PR
# Picks the #1 priority from reports/backlog.md, implements it autonomously,
# and opens a draft PR.
# =============================================================================

set -e

# Resolve project directory (works from launchd and manual invocation)
if [ -n "$GLIMMER_PROJECT_DIR" ]; then
  PROJECT_DIR="$GLIMMER_PROJECT_DIR"
else
  PROJECT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
fi
cd "$PROJECT_DIR"

LOG_FILE="$PROJECT_DIR/logs/auto-compound.log"
mkdir -p "$PROJECT_DIR/logs"

exec >> "$LOG_FILE" 2>&1
echo ""
echo "=========================================="
echo "Auto-Compound: $(date)"
echo "=========================================="

# Source environment if available
if [ -f "$PROJECT_DIR/app/.env.local" ]; then
  source "$PROJECT_DIR/app/.env.local"
fi

# Ensure we're on main with latest (including tonight's CLAUDE.md updates)
git checkout main
git fetch origin main
git reset --hard origin/main

# Step 1: Analyze backlog and pick #1 priority
echo ""
echo "Step 1: Analyzing backlog..."

ANALYSIS=$("$PROJECT_DIR/scripts/compound/analyze-backlog.sh")
echo "Analysis result: $ANALYSIS"

PRIORITY_ITEM=$(echo "$ANALYSIS" | python3 -c "import sys,json; print(json.load(sys.stdin).get('priority_item',''))" 2>/dev/null || echo "")
BRANCH_NAME=$(echo "$ANALYSIS" | python3 -c "import sys,json; print(json.load(sys.stdin).get('branch_name',''))" 2>/dev/null || echo "")
DETAILS=$(echo "$ANALYSIS" | python3 -c "import sys,json; print(json.load(sys.stdin).get('details',''))" 2>/dev/null || echo "")

if [ -z "$PRIORITY_ITEM" ] || [ "$PRIORITY_ITEM" = "null" ]; then
  echo "No priority items found in backlog. Nothing to do."
  exit 0
fi

echo "Priority: $PRIORITY_ITEM"
echo "Branch: $BRANCH_NAME"

# Step 2: Create feature branch
echo ""
echo "Step 2: Creating feature branch..."
git checkout -b "$BRANCH_NAME"

# Step 3: Create PRD (Product Requirements Document)
echo ""
echo "Step 3: Creating PRD..."

PRD_FILE="tasks/prd-$(echo "$BRANCH_NAME" | sed 's/feature\///')-$(date +%Y%m%d).md"

claude -p "You are a product manager for the 拾光 Glimmer project (AI memorial video platform).

Create a concise PRD (Product Requirements Document) for this feature:
**$PRIORITY_ITEM**

Details: $DETAILS

Read the existing codebase (CLAUDE.md, key files) to understand the architecture.

Write the PRD to: $PRD_FILE

The PRD should include:
1. Overview (2-3 sentences)
2. Requirements (bulleted list, specific and testable)
3. Technical approach (which files to modify, patterns to follow)
4. Acceptance criteria (how to verify it works)

Keep it concise — this will be converted to tasks next." \
  --dangerously-skip-permissions

# Step 4: Convert PRD to tasks JSON
echo ""
echo "Step 4: Converting PRD to tasks..."

claude -p "Read the PRD at $PRD_FILE.

Convert it into a task list and save as scripts/compound/prd.json with this format:
{
  \"feature\": \"$PRIORITY_ITEM\",
  \"branch\": \"$BRANCH_NAME\",
  \"created\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",
  \"tasks\": [
    {
      \"id\": 1,
      \"title\": \"Short task title\",
      \"description\": \"What to do\",
      \"status\": \"pending\",
      \"files\": [\"list of files to touch\"]
    }
  ]
}

Break the PRD into 3-8 small, atomic tasks. Each task should be completable in one iteration.
Order tasks by dependency (earlier tasks first).
Include a final task for 'build verification'." \
  --dangerously-skip-permissions

# Step 5: Run execution loop
echo ""
echo "Step 5: Running execution loop..."
"$PROJECT_DIR/scripts/compound/loop.sh" 25

# Step 6: Push and create PR
echo ""
echo "Step 6: Creating PR..."
git push -u origin "$BRANCH_NAME"

# Create draft PR
if command -v gh &> /dev/null; then
  gh pr create \
    --draft \
    --title "Compound: $PRIORITY_ITEM" \
    --body "## Auto-Compound PR

**Priority item**: $PRIORITY_ITEM

This PR was autonomously generated by the nightly compound system.

### What happened
1. Compound Review updated CLAUDE.md with today's learnings
2. Auto-Compound picked this as the #1 priority from the backlog
3. Created PRD and task list
4. Executed tasks iteratively until complete

### Review checklist
- [ ] Code changes look correct
- [ ] Build passes
- [ ] No unintended side effects

---
Generated at $(date)" \
    --base main
  echo "Draft PR created!"
else
  echo "gh CLI not available — please create PR manually at:"
  echo "https://github.com/jazzpujols34/glimmer/pull/new/$BRANCH_NAME"
fi

# Step 7: Update backlog — mark item as [IN PROGRESS]
git checkout main
git pull origin main
claude -p "Read reports/backlog.md. Find the item matching '$PRIORITY_ITEM' and change its status to [IN PROGRESS]. Add a note: 'PR: $BRANCH_NAME ($(date +%Y-%m-%d))'. Commit and push to main." \
  --dangerously-skip-permissions

echo ""
echo "Auto-compound complete: $(date)"
echo "=========================================="
